[package]
name = "aglassoflemonade"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
wasm-logger = "0.2.0"
yew = {version = "0.21.0", features = ["csr"]}
# yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = "0.18.0"
